### ISSUE TITLE
How do I run the generated LaTeX?

### ISSUE THREAD

**Issue by chrylis** [igneus/pslm#1]
I have been able to get `pslm` running, but it generates LaTeX that creates a `psalmus` environment. I have not been able to find a matching environment on CTAN, and the documentation here does not describe it. Where can I find it?

**Comment by igneus** [comment]
You don't - you define the environment yourself. (Depending on options you may need to define some additional LaTeX commands as well.)

The simplest case - do nothing, just define the environment so the LaTeX document builds without error:

```latex
\newenvironment{psalmus}{}{}
```

I often typeset psalms in two columns:

```latex
\newenvironment{psalmus}{\begin{multicols}{2}}{\end{multicols}}
```

Recently I've done this:

```latex
\newenvironment{psalmus}{%
\begin{adjustwidth}{0.8cm}{0cm}% psalms are narrower than the surrounding content to stand out
\leftskip=0.4cm \parindent=-\leftskip% hanging paragraphs
}{\end{adjustwidth}}
```

etc.

If you are trying to use `pslm` for something serious, I should probably warn you in advance that the software suffers a lot by a lack of love from my part. Not only it's underdocumented, it also has quite a lot of functionality not available through the command line interface (as I've been mostly using it as a library called from other utilities coded in Ruby) and the code is not a good example of either software design or coding. It's really just a messy utility I wrote in a hurry years ago, in the middle of a typesetting project with a deadline, and I almost haven't touched it since then.

**Comment by igneus** [comment]
The answer seems to be answered. Closing the issue due to inactivity.

**Comment by chrylis** [comment]
Thanks for the explanation. I ended up using it to generate a first-pass formatting and tweaked the output directly.
